project/urls.py
from django.conf.urls import patterns, url
from project import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = patterns('',
                       url(r'^$', views.home, name='home'),
                       url(r'^users/$', views.UserList.as_view(), name='user_list'),
                       url(r'^users/(?P<pk>\d+)/$', views.UserDetail.as_view(), name='user_detail'),
                       url(r'^users/add/$', views.AddUser.as_view(), name="user_add"),
                       url(r'^users/(?P<pk>\d+)/delete/$', views.DeleteUser.as_view(), name="user_delete"),
                       url(r'^users/(?P<pk>\d+)/edit/$', views.UpdateUser.as_view(), name="user_update"),
                       url(r'^users/(\d+)/reporte/userstories/$', views.reporte_userstories_user, name="reporte_userstories_user"),
                       url(r'^projects/$', views.ProjectList.as_view(), name='project_list'),
                       url(r'^projects/cancelled$', views.ProjectList.as_view(show_cancelled=True), name='project_list_cancelled'),
                       url(r'^projects/add/$', views.ProjectCreate.as_view(), name='project_create'),
                       url(r'^projects/(?P<pk>\d+)/edit/$', views.ProjectUpdate.as_view(), name='project_update'),
                       url(r'^projects/(?P<pk>\d+)/delete/$', views.ProjectDelete.as_view(), name='project_delete'),
                       url(r'^projects/(?P<pk>\d+)/aprobar/$', views.ApproveProject.as_view(), name='project_aprobar'),
                       url(r'^projects/(?P<pk>\d+)/$', views.ProjectDetail.as_view(), name='project_detail'),
                       url(r'^projects/(?P<project_pk>\d+)/flujo/$',views.FlujoList.as_view(),name='flujo_list'),
                       url(r'^projects/(?P<proyecto_id>\d+)/reporte/backlog/$',views.reporte_backlog_producto, name='reporte_backlog_producto'),
                       url(r'^projects/(?P<proyecto_id>\d+)/reporte/lista_priorizada/$',views.reporte_lista_priorizada, name='reporte_lista_priorizada'),
                       url(r'^projects/(?P<proyecto_id>\d+)/reporte/equipo/$',views.reporte_equipo_proyecto, name='reporte_equipo_proyecto'),
                        url(r'^projects/(?P<proyecto_id>\d+)/reporte/burndown/$', views.reporte_burndown, name='reporte_burndown'),
                       url(r'^flujo/(?P<pk>\d+)/$', views.FlujoDetail.as_view(), name='flujo_detail'),
                       url(r'^flujo/(?P<pk>\d+)/sprint/(?P<sprint_pk>\d+)/$', views.FlujoDetailSprint.as_view(), name='flujo_detail_sprint'),
                       url(r'^projects/(?P<project_pk>\d+)/flujo/add/$', views.AddFlujo.as_view(), name="flujo_add"),
                       url(r'^projects/(?P<project_pk>\d+)/flujo/addfromtemplate/$', views.CreateFromPlantilla.as_view(), name="flujo_addfromtemplate"),
                       url(r'^flujo/(?P<pk>\d+)/edit/$', views.UpdateFlujo.as_view(), name="flujo_update"),
                       url(r'^flujo/(?P<pk>\d+)/delete/$', views.DeleteFlujo.as_view(), name="flujo_delete"),
                       url(r'^projects/(?P<project_pk>\d+)/userstories/$', views.UserStoriesList.as_view(),name='product_backlog'),
                       url(r'^projects/(?P<project_pk>\d+)/userstories/pending/$', views.ApprovalPendingUserStories.as_view(),name='pending_userstories'),
                       url(r'^userstory/(?P<pk>\d+)/$', views.UserStoryDetail.as_view(), name='userstory_detail'),
                       url(r'^projects/(?P<project_pk>\d+)/userstories/add/$', views.AddUserStory.as_view(), name="userstory_add"),
                       url(r'^userstory/(?P<pk>\d+)/edit/$', views.UpdateUserStory.as_view(), name="userstory_update"),
                       url(r'^userstory/(?P<pk>\d+)/registrar/$', views.RegistrarActividadUserStory.as_view(), name="userstory_registraractividad"),
                       url(r'^userstory/(?P<pk>\d+)/delete/$', views.DeleteUserStory.as_view(), name="userstory_delete"),
                       url(r'^userstory/(?P<pk>\d+)/aprobar/$', views.ApproveUserStory.as_view(), name="userstory_aprobar"),
                       url(r'^userstory/(?P<pk>\d+)/rechazar/$', views.RechazarUserStory.as_view(), name="userstory_rechazar"),
                       url(r'^userstory/(?P<pk>\d+)/cancelar/$',views.CancelUserStory.as_view(),name="userstory_cancelar"),
                       url(r'^userstory/(?P<pk>\d+)/version/$', views.VersionList.as_view(), name="version_list"),
                       url(r'^userstory/(?P<pk>\d+)/revert/(?P<version_pk>\d+)/$', views.UpdateVersion.as_view(), name="version_revert"),
                       url(r'^userstory/(?P<pk>\d+)/files/$', views.FileList.as_view(), name="file_list"),
                       url(r'^userstory/(?P<pk>\d+)/files/upload/$', views.UploadFileView.as_view(), name="file_upload"),
                       url(r'^file/(?P<pk>\d+)/$', views.FileDetail.as_view(), name="file_detail"),
                       url(r'^nota/(?P<pk>\d+)/$', views.NotaDetail.as_view(), name='nota_detail'),
                       url(r'^userstory/(?P<pk>\d+)/notas/$', views.NotaList.as_view(), name="nota_list"),
                       url(r'^roles/$', views.RolList.as_view(), name='rol_list'),
                       url(r'^roles/(?P<pk>\d+)/$', views.RolDetail.as_view(), name='rol_detail'),
                       url(r'^roles/add/$', views.AddRolView.as_view(), name="rol_add"),
                       url(r'^roles/(?P<pk>\d+)/edit/$', views.UpdateRolView.as_view(), name="rol_update"),
                       url(r'^roles/(?P<pk>\d+)/delete/$', views.DeleteRolView.as_view(), name="rol_delete"),
                       url(r'^attachment/(?P<pk>\d+)/$', views.download_attachment, name='download_attachment'),
                       url(r'^projects/(?P<project_pk>\d+)/sprint/add/$', views.AddSprintView.as_view(), name="sprint_add"),
                       url(r'^sprint/(?P<pk>\d+)/$', views.SprintDetail.as_view(), name='sprint_detail'),
                       url(r'^projects/(?P<project_pk>\d+)/sprint/$', views.SprintList.as_view(),name="sprint_list"),
                       url(r'^sprint/(?P<pk>\d+)/edit/$', views.UpdateSprintView.as_view(), name="sprint_update"),

                       url(r'^plantilla/$',views.PlantillaList.as_view(),name='plantilla_list'),
                       url(r'^plantilla/(?P<pk>\d+)/$', views.PlantillaDetail.as_view(), name='plantilla_detail'),
                       url(r'^plantilla/add/$', views.AddPlantilla.as_view(), name="plantilla_add"),
                       url(r'^plantilla/(?P<pk>\d+)/delete/$', views.DeletePlantilla.as_view(), name="plantilla_delete"),
                       url(r'^plantilla/(?P<pk>\d+)/edit/$', views.UpdatePlantilla.as_view(), name="plantilla_update"),

                       url(r'^sprint/(?P<pk>\d+)/burndown/$', views.SprintBurndown.as_view(), name='sprint_burndown'),
                       url(r'^morris/(?P<sprint_pk>\d+)/generate/$', views.generarNotas, name='generate'),
                       url(r'^sprint/(\d+)/reporte/backlog/$',views.reporte_backlog_sprint, name='reporte_backlog_sprint'),
                       )

projectium/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin

urlpatterns = patterns('',
                       url(r'^admin/doc/', include('django.contrib.admindocs.urls')),
                       url(r'^admin/', include(admin.site.urls)),
                       url(r'^', include('authentication.urls', namespace='authentication')),
                       url(r'^', include('project.urls', namespace='project')),
                       )

project/models.py
# -*- coding: utf-8 -*-
from base64 import b64encode
from django.db import models
from django.contrib.auth.models import User, Group
from django.core.exceptions import ValidationError
from django.db.models import Q, Sum
from django.db.models.signals import m2m_changed, post_save
from django.shortcuts import get_object_or_404
from django.utils.encoding import force_bytes
from django.utils import timezone
from guardian.shortcuts import assign_perm, remove_perm, get_perms_for_model, get_perms
from django.core.urlresolvers import reverse_lazy
import reversion
from reversion.models import Revision


class Proyecto(models.Model):
    """
    Modelo de Proyecto del sistema.

    """
    estado_choices = (
        ('EP', 'En Produccion'), ('CO', 'Completado'), ('AP', 'Aprobado'), ('CA', 'Cancelado'), ('IN', 'Inactivo'))
    nombre_corto = models.CharField(max_length=20)
    nombre_largo = models.CharField(max_length=40)
    estado = models.CharField(choices=estado_choices, max_length=2, default='IN')
    inicio = models.DateTimeField()
    fin = models.DateTimeField()
    creacion = models.DateTimeField(auto_now_add=True)
    duracion_sprint = models.PositiveIntegerField(default=30)
    descripcion = models.TextField()
    equipo = models.ManyToManyField(User, through='MiembroEquipo')

    class Meta:
        # Los permisos estaran asociados a los proyectos, por lo que todos los permisos de ABM de las entidades
        #dependientes del proyecto, deben crearse como permisos de proyecto
        #en vez de 'add', 'change' y 'delete', los permisos personalizados seran 'create', 'edit' y 'remove' para
        #evitar confusiones con los por defecto.

        permissions = (
            ('list_all_projects', 'listar los proyectos disponibles'),
            ('view_project', 'ver el proyecto'),
            ('aprobar_proyecto', 'aprobar el proyecto'),

            ('create_sprint', 'agregar sprint'),
            ('edit_sprint', 'editar sprint'),
            ('remove_sprint', 'eliminar sprint'),

            ('create_flujo', 'agregar flujo'),
            ('edit_flujo', 'editar flujo'),
            ('remove_flujo', 'eliminar flujo'),

            ('create_userstory', 'agregar userstory'),
            ('edit_userstory', 'editar userstory'),
            ('remove_userstory', 'eliminar userstory'),
            ('prioritize_userstory', 'asignar prioridad a userstories'),
            ('registraractividad_userstory', 'registrar avances en userstories'),
            ('aprobar_userstory', 'aprobar userstories completados'),
            ('cancelar_userstory', 'cancela userstories completados'),

            #TODO: Hace falta definir permisos para Notas y Adjuntos?
        )

    def __unicode__(self):
        return self.nombre_corto

    def get_absolute_url(self):
        return reverse_lazy('project:project_detail', args=[self.pk])

    def get_horas_estimadas(self):
        return self.userstory_set.aggregate(total=Sum('tiempo_estimado'))['total']

    def get_horas_trabajadas(self):
        return self.userstory_set.aggregate(total=Sum('tiempo_registrado'))['total']

    def _get_progreso(self):
        us_total = self.userstory_set.count() - self.userstory_set.filter(estado=4).count()
        us_aprobados = self.userstory_set.filter(estado=3).count()
        progreso = float(us_aprobados) / us_total * 100 if us_total > 0 else 0
        return int(progreso)
    progreso = property(_get_progreso)

    def clean(self):
        try:
            if self.inicio > self.fin:
                raise ValidationError({'inicio': 'Fecha de inicio no puede ser mayor '
                                                 'que la fecha de terminacion.'})
        except TypeError:
            pass  # si una de las fechas es null, clean_field() se encarga de lanzar error


class MiembroEquipo(models.Model):
    """
    Miembros del equipo de un proyecto con un rol específico
    """
    usuario = models.ForeignKey(User)
    proyecto = models.ForeignKey(Proyecto)
    roles = models.ManyToManyField(Group)
    '''
    def __unicode__(self):
        return "{} - {}:{}".format(self.proyecto, self.usuario, self.roles.all())
    '''

    def save(self, force_insert=False, force_update=False, using=None,
             update_fields=None):
        super(MiembroEquipo, self).save(force_insert, force_update, using, update_fields)
        # Agregamos el permiso view_proyect al usuario
        assign_perm('view_project', self.usuario, self.proyecto)


    # nota: si se quiere hacer un bulk delete a través de un queryset no hacerlo directamente
    #llamar al delete de cada objeto para remover los permisos
    def delete(self, using=None):
        for role in self.roles.all():
            for perm in role.permissions.all():
                remove_perm(perm.codename, self.usuario, self.proyecto)
        super(MiembroEquipo, self).delete(using)

    class Meta:
        default_permissions = ()
        verbose_name_plural = 'miembros equipo'
        unique_together = ('usuario', 'proyecto')


class Sprint(models.Model):
    """
    Manejo de los sprints del proyecto
    """
    nombre = models.CharField(max_length=20)
    inicio = models.DateTimeField()
    fin = models.DateTimeField()
    proyecto = models.ForeignKey(Proyecto, null=False, blank=True)
    #estado = models.BooleanField(default=False)

    class Meta:
        default_permissions = ()
        verbose_name = 'sprint'
        verbose_name_plural = 'sprints'

    def __unicode__(self):
        return self.nombre

    def get_absolute_url(self):
        return reverse_lazy('project:sprint_detail', args=[self.pk])




class Flujo(models.Model):
    """
    Administración de los flujos que forman parte de un proyecto.
    Las plantillas de flujo se manejan como Flujos sin proyecto asignado.
    """
    nombre = models.CharField(max_length=20)
    proyecto = models.ForeignKey(Proyecto, null=True, blank=True)

    def __unicode__(self):
        return self.nombre

    class Meta:
        verbose_name_plural = 'flujos'
        default_permissions = ()
        permissions = (
            ('add_flow_template', 'agregar plantilla de flujo'),
            ('change_flow_template', 'editar plantilla de flujo'),
            ('delete_flow_template', 'eliminar plantilla de flujo'),
        )

    def get_absolute_url(self):
        return reverse_lazy('project:flujo_detail', args=[self.pk])


class Actividad(models.Model):
    """
    Las actividades representan las distintas etapas de las que se componen un flujo
    """
    name = models.CharField(max_length=20)
    flujo = models.ForeignKey(Flujo)

    def __unicode__(self):
        return self.name

    class Meta:
        order_with_respect_to = 'flujo'
        verbose_name_plural = 'actividades'


class UserStory(models.Model):
    """
    Manejo de los User Stories. Los User Stories representan a cada
    funcionalidad desde la perspectiva del cliente que debe realizar el sistema.
    """
    estado_actividad_choices = ((0, 'ToDo'), (1, 'Doing'), (2, 'Done'), )
    estado_choices = ((0, 'Inactivo'), (1, 'En curso'), (2, 'Pendiente Aprobacion'), (3, 'Aprobado'), (4,'Cancelado'),)
    priority_choices = ((0, 'Baja'), (1, 'Media'), (2, 'Alta'))
    nombre = models.CharField(max_length=60)
    descripcion = models.TextField()
    prioridad = models.IntegerField(choices=priority_choices, default=0)
    valor_negocio = models.IntegerField()
    valor_tecnico = models.IntegerField()
    tiempo_estimado = models.PositiveIntegerField()
    tiempo_registrado = models.PositiveIntegerField(default=0)
    ultimo_cambio = models.DateTimeField(auto_now=True)
    estado = models.IntegerField(choices=estado_choices, default=0)
    estado_actividad = models.IntegerField(choices=estado_actividad_choices, default=0)
    proyecto = models.ForeignKey(Proyecto)
    desarrollador = models.ForeignKey(User, null=True, blank=True)
    sprint = models.ForeignKey(Sprint, null=True, blank=True)
    actividad = models.ForeignKey(Actividad, null=True, blank=True)

    def __unicode__(self):
        return self.nombre

    def _get_progreso(self):
        progreso = float(self.tiempo_registrado) / self.tiempo_estimado * 100
        return int(progreso if progreso <= 100 else 100)
    progreso = property(_get_progreso)

    def get_absolute_url(self):
        return reverse_lazy('project:userstory_detail', args=[self.pk])

    def save(self, force_insert=False, force_update=False, using=None,
             update_fields=None):
        old_developer = None

        if self.pk is not None:
            old_instance = get_object_or_404(UserStory, pk=self.pk)
            old_developer = old_instance.desarrollador
        super(UserStory, self).save(force_insert, force_update, using, update_fields)
        #borramos los permisos del antiguo desarrollador
        if old_developer:
            for perm in get_perms(old_developer, self):
                remove_perm(perm, old_developer, self)
        #copiamos al user story recién creado los permisos de user story
        if self.proyecto and self.desarrollador:
            membership = get_object_or_404(MiembroEquipo, usuario=self.desarrollador, proyecto=self.proyecto)
            permisos_us = get_perms_for_model(UserStory)
            for rol in membership.roles.all():
                for perm in rol.permissions.all():
                    if perm in permisos_us:
                        assign_perm(perm.codename, self.desarrollador, self)

    class Meta:
        verbose_name_plural = 'user stories'
        default_permissions = ()
        permissions = (
            ('edit_my_userstory', 'editar mis userstories'),
            ('registraractividad_my_userstory', 'registrar avances en mis userstories')
        )


reversion.register(UserStory,
                   fields=['nombre', 'descripcion', 'prioridad', 'valor_negocio', 'valor_tecnico', 'tiempo_estimado'])
#importamos recién acá la señal para que no haya la dependencia circular entre la señal y UserStory

project/templates/project/base.html
{% extends 'base.html' %}

{% block base %}
    <div id="wrapper">

        <!-- Navigation -->
        <nav class="navbar navbar-default navbar-static-top" role="navigation" style="margin-bottom: 0">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="{% url 'project:home' %}">Projectium</a>
            </div>
            <ul class="nav navbar-nav">
                <ul class="breadcrumb">
                  {% block breadcrumbs %}<li class="active">Home</li>{% endblock %}
                </ul>
            </ul>
            <!-- /.navbar-header -->
            <ul class="nav navbar-top-links navbar-right">
                <li class="dropdown">
                    <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                        <i class="fa fa-dashboard fa-fw"></i> <i class="fa fa-caret-down"></i>
                    </a>
                    <ul class="dropdown-menu dropdown-tasks">
                        {% for p in nav_projects %}
                        <li>
                            <a href="{% url 'project:project_detail' p.id %}">
                                <div>
                                    <p>
                                        <strong>{{ p }}</strong>
                                        <span class="pull-right text-muted">{{ p.progreso }}% Complete</span>
                                    </p>

                                    <div class="progress progress-striped active">
                                        <div class="progress-bar" role="progressbar"
                                             aria-valuenow="{{ p.progreso }}" aria-valuemin="0" aria-valuemax="100"
                                             style="width: {{ p.progreso }}%">
                                            <span class="sr-only">{{ p.progreso }}% Complete (success)</span>
                                        </div>
                                    </div>
                                </div>
                            </a>
                        </li>
                        <li class="divider"></li>
                        {% endfor %}
                        <li>
                            <a class="text-center" href="{% url 'project:project_list' %}">
                                <strong>Ver todos los proyectos</strong>
                                <i class="fa fa-angle-right"></i>
                            </a>
                        </li>
                    </ul>
                    <!-- /.dropdown-tasks -->
                </li>
                <li class="dropdown">
                    <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                        <i class="fa fa-tasks fa-fw"></i> <i class="fa fa-caret-down"></i>
                    </a>
                    <ul class="dropdown-menu dropdown-tasks">
                        {% for u in nav_us %}
                        <li>
                            <a href="{% url 'project:userstory_detail' u.id %}">
                                <div>
                                    <p>
                                        <strong>{{ u|truncatechars:"25" }}</strong>
                                        <span class="pull-right text-muted">{{ u.progreso }}% Complete</span>
                                    </p>

                                    <div class="progress progress-striped active">
                                        <div class="progress-bar" role="progressbar"
                                             aria-valuenow="{{ u.progreso }}" aria-valuemin="0" aria-valuemax="100"
                                             style="width: {{ u.progreso }}%">
                                            <span class="sr-only">{{ u.progreso }}% Complete (success)</span>
                                        </div>
                                    </div>
                                </div>
                            </a>
                        </li>
                        <li class="divider"></li>
                        {% endfor %}
                        <li>
                            <a class="text-center" href="{% url 'project:user_detail' user.id %}#user_stories">
                                <strong>Ver User Stories</strong>
                                <i class="fa fa-angle-right"></i>
                            </a>
                        </li>
                    </ul>
                    <!-- /.dropdown-tasks -->
                </li>
                <!-- /.dropdown -->

                <li class="dropdown">
                    <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                        <i class="fa fa-user fa-fw"></i> <i class="fa fa-caret-down"></i>
                    </a>
                    <ul class="dropdown-menu dropdown-user">
                        <li><a href="{% url 'project:user_detail' user.id %}"><i
                                class="fa fa-user fa-fw"></i> {{ user.username }}</a>
                        </li>
                        <li><a href="{% url 'authentication:password_change' %}"><i class="fa fa-gear fa-fw"></i> Cambiar
                            Password</a>
                        </li>
                        <li class="divider"></li>
                        <li><a href="{% url 'authentication:logout' %}"><i class="fa fa-sign-out fa-fw"></i> Logout</a>
                        </li>
                    </ul>
                    <!-- /.dropdown-user -->
                </li>
                <!-- /.dropdown -->
            </ul>
            <!-- /.navbar-top-links -->

            <div class="navbar-default sidebar" role="navigation">
                <div class="sidebar-nav navbar-collapse">
                    <ul class="nav" id="side-menu">

                        <li>
                            <a href="{% url 'project:project_list' %}"><i class="fa fa-dashboard fa-fw"></i>
                                Proyectos</a>
                        </li>
                        <li>
                            <a href="{% url 'project:user_list' %}"><i class="fa fa-user fa-fw"></i> Users</a>
                        </li>
                        <li>
                            <a href="{% url 'project:rol_list' %}"><i class="fa fa-group fa-fw"></i> Roles</a>
                        </li>
                        <li>
                            <a href="{% url 'project:plantilla_list' %}"><i class="fa fa-columns fa-fw"></i> Plantillas</a>
                        </li>
                    </ul>
                </div>
                <!-- /.sidebar-collapse -->
            </div>
            <!-- /.navbar-static-side -->
        </nav>


        <div id="page-wrapper">
            <div class="row">
                <div class="col-lg-12">
                    <h1 class="page-header">{% block header %}{% endblock %}</h1>
                </div>
                <!-- /.col-lg-12 -->
            </div>
            <!-- /.row -->
            <div id="content">
                <div class="row">
                    <div class="col-lg-12">
                    {% block content %}
                    {% endblock %}
                    </div>
                </div>
            </div>
        </div>
        <!-- /#page-wrapper -->
    </div>
    <!-- /#wrapper -->

{% endblock %}

project/templates/project/home.html
{% extends 'project/base.html' %}
{% block title %}Home{% endblock %}
{% block header %}Bienvenido {{ user.username|title }}{% endblock %}
{% block content %}
    <div class="row">
        <div class="col-lg-3 col-md-6">
            <div class="panel panel-primary">
                <div class="panel-heading">
                    <div class="row">
                        <div class="col-xs-3">
                            <i class="fa fa-dashboard fa-5x"></i>
                        </div>
                        <div class="col-xs-9 text-right">
                            <div class="huge">{{ user.miembroequipo_set.count }}</div>
                            <div>Proyectos</div>
                        </div>
                    </div>
                </div>
                <a href="{% url 'project:project_list' %}">
                    <div class="panel-footer">
                        <span class="pull-left">View Details</span>
                        <span class="pull-right"><i class="fa fa-arrow-circle-right"></i></span>

                        <div class="clearfix"></div>
                    </div>
                </a>
            </div>
        </div>
        <div class="col-lg-3 col-md-6">
            <div class="panel panel-green">
                <div class="panel-heading">
                    <div class="row">
                        <div class="col-xs-3">
                            <i class="fa fa-user fa-5x"></i>
                        </div>
                        <div class="col-xs-9 text-right">
                            <div class="huge">{{ users_count }}</div>
                            <div>Usuarios</div>
                        </div>
                    </div>
                </div>
                <a href="{% url 'project:user_list' %}">
                    <div class="panel-footer">
                        <span class="pull-left">View Details</span>
                        <span class="pull-right"><i class="fa fa-arrow-circle-right"></i></span>

                        <div class="clearfix"></div>
                    </div>
                </a>
            </div>
        </div>
        <div class="col-lg-3 col-md-6">
            <div class="panel panel-yellow">
                <div class="panel-heading">
                    <div class="row">
                        <div class="col-xs-3">
                            <i class="fa fa-table fa-5x"></i>
                        </div>
                        <div class="col-xs-9 text-right">
                            <div class="huge">{{ plantillas_count }}</div>
                            <div>Plantillas</div>
                        </div>
                    </div>
                </div>
                <a href="{% url 'project:plantilla_list' %}">
                    <div class="panel-footer">
                        <span class="pull-left">View Details</span>
                        <span class="pull-right"><i class="fa fa-arrow-circle-right"></i></span>

                        <div class="clearfix"></div>
                    </div>
                </a>
            </div>
        </div>
        <div class="col-lg-3 col-md-6">
            <div class="panel panel-red">
                <div class="panel-heading">
                    <div class="row">
                        <div class="col-xs-3">
                            <i class="fa fa-file fa-5x"></i>
                        </div>
                        <div class="col-xs-9 text-right">
                            <div class="huge">{{ us_count }}</div>
                            <div>User Stories</div>
                        </div>
                    </div>
                </div>
                <a href="{% url 'project:user_detail' user.id %}#user_stories">
                    <div class="panel-footer">
                        <span class="pull-left">View Details</span>
                        <span class="pull-right"><i class="fa fa-arrow-circle-right"></i></span>

                        <div class="clearfix"></div>
                    </div>
                </a>
            </div>
        </div>
    </div>

{% endblock %}

project/templates/project/user_list.html
{% extends 'project/base.html'%}
{% load staticfiles %}
{% block title %}Usuarios{% endblock %}
{% block header %}Usuarios{% endblock %}
{% block content %}
{% if perms.auth.add_user %}<p><a href="{% url 'project:user_add' %}" class="fa fa-plus-circle">Agregar</a></p>{% endif %}
<div class="dataTable_wrapper">
    <table class="table table-striped table-bordered table-hover" id="myTable">
        <thead>
            <tr>
                <th>Username</th>
                <th>Nombre</th>
                <th>Apellido</th>
                <th>Ultimo Login</th>
                <th>Ver</th>
                {% if perms.auth.change_user %}<th>Editar</th>{% endif %}
                {% if perms.auth.delete_user %}<th>Eliminar</th>{% endif %}
            </tr>
        </thead>
        <tbody>
            {% for u in users %}
            <tr class="odd gradeX">
                <td>{{ u.username }}</td>
                <td>{{ u.first_name }}</td>
                <td>{{ u.last_name }}</td>
                <td>{{ u.last_login }}</td>
                <td ><a href="{% url 'project:user_detail' u.id %}"><i class="fa fa-eye fa-fw"></i></a> </td>
                {% if perms.auth.change_user %}<td><a href="{% url 'project:user_update' u.id %}"><i class="fa fa-pencil fa-fw"></i></a></td>{% endif %}
                {% if perms.auth.delete_user %}<td><a href="{% url 'project:user_delete' u.id %}"><i class="fa fa-trash-o fa-fw"></i></a></td>{% endif %}
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>
<!-- /.table-responsive -->
{% endblock %}

{% block extra_js %}

    <!-- jQuery -->
<script type="text/javascript" charset="utf8" src="//code.jquery.com/jquery-1.10.2.min.js"></script>

<!-- DataTables -->
<script src="{% static 'bower_components/datatables/media/js/jquery.dataTables.min.js' %}"></script>
<script src="{% static 'bower_components/datatables-plugins/integration/bootstrap/3/dataTables.bootstrap.min.js' %}"></script>

<script>
$(document).ready(function() {
    $('#myTable').DataTable({
            responsive: true
    });
});
</script>
{% endblock %}